### PR TITLE
Creating program and documentation of insertion sort using C++ for issue#36

### PR DESCRIPTION
**Pull request by shriyaMadan**
issue #36

### CODE REVIEW

**Comment by Zircoz** [comment]
Issue#36

**Comment by Zircoz** [comment]
#36

**Comment by shriyaMadan** [comment]
updated documentation and pseudo code

**Comment by shriyaMadan** [comment]
issue #36

**Comment by shriyaMadan** [comment]
PR is created with updated documentation @Sjsingh101

**Pull request merged**
